POST http://127.0.0.1:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "Joni",
  "password": "1234"
}

###
POST http://127.0.0.1:3000/api/v1/auth/login
Content-Type: application/json

{
"username": "Joni",
"password": "salasana"
}

